### ISSUE TITLE
"Edit me" buttons

### ISSUE THREAD

**Issue by hugovk** [botwiki/botwiki.org#26]
Would it be possible to add some sort of "Edit me" or "Contribute to docs" on each page?

A bit like this: https://pantheon.io/docs/articles/sites/code/redirect-incoming-requests/ or even just a simple link to edit would be great. 

It'll help make it more obvious that things can be edited, and encourage people to contribute.

**Comment by stefanbohacek** [comment]
Yes, I thought about that! Will definitely look into this.

**Comment by stefanbohacek** [comment]
So this turns out to be a bit tricky. https://github.com/picocms/Pico/issues/210

**Comment by stefanbohacek** [comment]
And it also looks this should be possible with the [upcoming Pico 1.0 release](https://github.com/picocms/Pico/pull/252). I'm just going to save the work in progress for now.
