### ISSUE TITLE
Minor updates to botshotter.py

### ISSUE THREAD

**Issue by stefanbohacek** [botwiki/botwiki.org#40]
@hugovk A few notes on the awesome script that you made -- mostly small stuff, let me know if you'd prefer me to take care of this myself.
- [x] add network tags based on bot's network, eg: if it's a Twitter bot, the tags should include `twitter` and `twitterbot` (we should also check for duplicate tags before saving them) (and for more inconsistency, network tags should never include space or - , so `youtubebot` is correct)
  - note on adding both `twitter` and `twitterbot`: this is pretty much future-proofing the content, in case we want to tag content that's, for example, about Twitter, but not actually a bot
- [x] remove @ from the image file name (in the actual .md file); also, some notes for the future, for non-Twitter bots:
  - spaces should be replaced with _
  - /u/ and /r/ should be removed
  - this is pretty much the same logic as (around the line) https://github.com/botwiki/botwiki.org/blob/master/themes/botwiki/search_results.html#L45
- [x] `twitter-bots` in the image path should be `twitterbots`
- [x] is there a way to apply pngcrush (or similar) on the images?
- [x] new line before and after the image thumbnail

**Comment by hugovk** [comment]
Yes, that stuff should be fine.

How do you normally run pngcrush? Can you give an example command?

**Comment by stefanbohacek** [comment]
I believe this will answer your question: https://github.com/botwiki/botwiki.org/issues/6 :-)

The reason for closing this was actually a bit misguided. I thought it would require keeping source images and saving optimized images separately, which is how I normally keep things (just in case, I suppose). It would make sense to just overwrite the screenshots in our case, so I think I'll look into reopening that issue.

Either way, I usually just use common/default values.

**Comment by hugovk** [comment]
Whilst looking at tags, should we change the case at all?

Does it matter if their order is changed when deduping? Do we want a specific order?

**Comment by stefanbohacek** [comment]
How about doing something like this (pseudocode):

```
switch (bot.type):
  case 'twitterbot':
    tags = ['twitter', 'twitterbot']
  break
// etc for other networks, then later
tags += user_submitted_tags 
          + (bot.is_opensource ? ['open source', 'opensource'] : ) 
          + author_twittername
// finally
tags.dedupe
```

I don't think the tag order particularly matters, but I would rather keep the order, which has been something like what the code above would produce.

This actually reminds me, we need to ask about the language for open source bots!

Oh and I'd definitely use lowercase. Thank you!

**Comment by stefanbohacek** [comment]
I added a question "If the bot is open source, what language was used to write it? (Or just leave blank.)".

**Comment by hugovk** [comment]
Did the new question shift the Added column one to the right? If so, I need to update for that too :)

**Comment by hugovk** [comment]
All but the pngcrush/Trimage addressed in #41.

It doesn't looks like Trimage has any Windows binaries, but pngcrush is more platform-independent.

Default options don't trim much:
- The original GenerateACat.png from botshotter.py is 440 KB.
- The one you optimised (with trimage?) and updated in the repo is 386 KB. 
- The pngcrushed one is 435 KB.

---

GenerateACat.botshotter.png:
![generateacat botshotter](https://cloud.githubusercontent.com/assets/1324225/10546219/62d0d71e-7435-11e5-8359-99e001eeb7d1.png)

---

GenerateACat.trimage.png:
![generateacat trimage](https://cloud.githubusercontent.com/assets/1324225/10546221/6744b860-7435-11e5-8bc6-a134e7278606.png)

---

GenerateACat.pngcrush.png:
![generateacat pngcrush](https://cloud.githubusercontent.com/assets/1324225/10546222/6b3b4c4a-7435-11e5-829f-4c3ee22b3d6c.png)

**Comment by stefanbohacek** [comment]
@hugovk Hmm, it looks like adding a new question adds a new column at the end, but before any manually added columns.

I just added a test submission, feel free to check it out and delete when done.

**Comment by hugovk** [comment]
>  Hmm, it looks like adding a new question adds a new column at the end, but before any manually added columns.

We'll have to remember that in future.

> I just added a test submission, feel free to check it out and delete when done.

Test submission seemed to be processed okay. Deleted.

**Comment by hugovk** [comment]
The Trimage shows it using OptiPNG, I'll look into that. https://github.com/Kilian/Trimage/blob/master/src/trimage/trimage.py#L435

**Comment by stefanbohacek** [comment]
@hugovk Awesome, thank you!
