### ISSUE TITLE
Organize site sections

### ISSUE THREAD

**Issue by stefanbohacek** [botwiki/botwiki.org#61]
- [x] https://botwiki.org/tutorials/twitterbots#tutorials, either by language and/or required skill level
- [x] https://botwiki.org/resources/public-datasets, create sub-categories for the main list
- [x] https://botwiki.org/resources/libraries-frameworks, mainly the node.js section, by category, I suppose

**Comment by hugovk** [comment]
By the way, on the last one, dariusk/wordfilter has node, Ruby and Python versions available in the same repo.

**Comment by stefanbohacek** [comment]
@hugovk Thanks, I'll update it!
