### ISSUE TITLE
Content translation

### ISSUE THREAD

**Issue by stefanbohacek** [botwiki/botwiki.org#63]
It would be really great if we could find volunteers that would translate the content into other languages. 

Is there perhaps a company offering translation services for free to open source projects? (Maybe not, but I was looking at [this](https://github.com/velikanov/opensource-candies).)

Or we can just wait until we have [enough funding](https://gratipay.com/botwiki-org/) :-)

Also, a technical note: I would like to keep the translated content in the same folder, so you could easily link to, for example, https://botwiki.org/bots/tumblr-bots/deadspelunkers_de.

[This](https://www.duolingo.com/translations/upload) _might_ be useful.

**Comment by hectorpalmatellez** [comment]
Hola, @fourtonfish: yo te puedo ayudar traduciendo a castellano de Latinoamérica 🇨🇱

**Comment by stefanbohacek** [comment]
@hectorpalmatellez Sounds great, at least when run through Google Translate :-)

Thank you! I'm going to look into the best way to manage this, for now I'm just going to accept volunteers.

[This](https://github.com/velikanov/opensource-candies#localization) could actually be really useful, I'll check it out some time later today/tomorrow.

Thanks, again, and have a great weekend!

**Comment by stefanbohacek** [comment]
Another thing to solve: where do we call out the existence of translated pages? The easiest would be
- under the title
- under the image
- somewhere at the bottom

I don't like it under the title, people may not notice it at the bottom (plus what's the point of seeing there's a translation in your language if you already read the page). Using https://botwiki.org/bots/tumblr-bots/deadspelunkers as an example, how does this look?

![screenshot from 2015-10-24 12 44 01](https://cloud.githubusercontent.com/assets/3909390/10711550/1976fdfa-7a4d-11e5-89fa-a7bf8b3a4b1a.png)

Note: The missing dot at the end is more or less a typo.

**Comment by hectorpalmatellez** [comment]
I remember this way of doing it:

![Opera Dev Blog](http://i.xewa.cl/f4Cmnpr2qr.png)
[Seen here.](https://dev.opera.com/articles/introducing-ecmascript-5.1/)

Maybe a little box floated to the right? In the same hierarchy as the title.

**Comment by stefanbohacek** [comment]
So I looked at the sites mentioned above, nothing too impressive. And I'm also not a huge fan of doing anything too fancy with CSS, I really prefer keeping the site simple and fast to load. (Did anyone notice we have lazy image loading with neat little loading effect, sleek mobile menu -- all without jQuery?)

Anyway, I'm actually not very happy about how the file is structured, see [here](https://github.com/botwiki/botwiki.org/blob/master/themes/botwiki/includes/article.html).

Basically, the two easiest options of placing the language links are these:

![position-2](https://cloud.githubusercontent.com/assets/3909390/10720572/32da2722-7b6f-11e5-8e1d-7b1dc203b460.png)
![position-1](https://cloud.githubusercontent.com/assets/3909390/10720573/32e21554-7b6f-11e5-9e5f-f2fb63ae91f8.png)

I think it looks a bit better on top. Making the line go under the image would require some heavy rewriting of the templates. Maybe add the banner image inside the metadata, or some find/replace stuff. Not a huge fan of doing either of these.

So my stance is:
1. simply write here which files you want to translate and to which languages, for example:
   - [ ] twitterbots/1_thing_idk_why -- Japanese
   - [x] tumblr-bots/deadspelunkers -- Italian
   
   Etc, then mark them as completed when the translation is done.
2. let's just have the metadata on top, above the title

**Comment by stefanbohacek** [comment]
Actually, another option is to have the links to translated pages on top, above the title, then date at its original location. I think I like that one the most.

**Comment by hectorpalmatellez** [comment]
:+1: 
When do we start? :smile:

**Comment by stefanbohacek** [comment]
@hectorpalmatellez

Seeing as you're the only volunteer right now, you're in full control :-)

Just clone the repo, create a copy of the files with the language code added to the filename, translate the description and the content -- I suppose we don't need to translate the tags...or should we?

We actually might also need to translate the "updated on" snippet...Maybe we should add an extra meta tag "Language"?

**Comment by stefanbohacek** [comment]
That way we can look at the language meta tag inside the view file and print out "last updated on" based on the value.

But should we then also translate the date...?

Hmm, this is getting a bit complicated.

**Comment by hectorpalmatellez** [comment]
Is there any scope to what should be translated? Just the bots or everything?

**Comment by stefanbohacek** [comment]
Alright, let's do it this way. Let's say you want to translate https://github.com/botwiki/botwiki.org/blob/master/content/bots/twitterbots/11_11_bot.md
1. Create a file `/content/bots/twitterbots/11_11_bot_xx.md` where `xx` is the [language code](https://www.loc.gov/standards/iso639-2/php/code_list.php) (ISO 639-1).
2. Looking at the [actual .md file](https://raw.githubusercontent.com/botwiki/botwiki.org/master/content/bots/twitterbots/11_11_bot.md), update the `Author` tag and add a new tag below called `Language: xx`, where `xx` is the [language code](https://www.loc.gov/standards/iso639-2/php/code_list.php)  (ISO 639-1).
3. Translate the content of the page, in this case 

```
[@11_11_bot](https://twitter.com/11_11_bot) is a Twitter bot created by [@swayandsea](https://twitter.com/swayandsea) that will remind of your own mortality, daily.
```

And that's it. We will also need to translate the following sentences, which I will update in the template file based on the `Language` meta tag.
- Last updated
- Browse more bots like this

I am going to keep the date format as it is now and worry about it later.

**Comment by hectorpalmatellez** [comment]
Just sent #70! :v:

**Comment by stefanbohacek** [comment]
@hectorpalmatellez Thank you!

Would you mind also translating these? Just here in a comment.
- Last updated
- Browse more bots like this

**Comment by hectorpalmatellez** [comment]
- Actualizado por última vez
- Otros bots como este

¡Listo!

**Comment by stefanbohacek** [comment]
@hectorpalmatellez Thanks, again!

Have a look at:
- https://botwiki.org/bots/twitterbots/_sys_bot_
- https://botwiki.org/bots/twitterbots/11_11_bot

For some reason https://botwiki.org/bots/twitterbots/1_thing_idk_why is giving me problems, still investigating.

I also made it so that the translated content doesn't appear in [search](https://botwiki.org/search?q=11_11) or when browsing [tags](https://botwiki.org/tag/death), which will make more sense once we have 4-5 languages per file :-)

And I was actually kind of forced to automate the detection of translated pages, so whenever you're free, can you have a look at https://github.com/botwiki/botwiki.org/blob/master/TRANSLATING-CONTENT.md and let me know if this makes sense?

(I will also have to ask you to go back and maybe change the dates in the translated files?)

Thank you!

**Comment by hectorpalmatellez** [comment]
Okay, I will do these edits in the translated files.

As for the translation instructions, maybe adding links to successfully translated files would become handy, when these exist :smiley: 

Seeing the translated files, I think «Puedes ver otros bots similares en:» is more accurate than just «otros bots como este».

**Comment by stefanbohacek** [comment]
Yeah, showing examples is a good idea.

However, it looks like I'm running into [this issue](https://github.com/picocms/Pico/issues/104).

**Comment by stefanbohacek** [comment]
A-ha! https://github.com/picocms/Pico/issues/140

**Comment by stefanbohacek** [comment]
I created a file with instructions for translators and added a link on top of the README.
