### ISSUE TITLE
Botshotter.py: taller Twitter screenshots?

### ISSUE THREAD

**Issue by hugovk** [botwiki/botwiki.org#65]
Currently Twitter imagebots aren't shown off to their best, some more vertical space would help. Shouldn't harm textbots either, another tweet or two might fit in.

Some examples:

![image](https://cloud.githubusercontent.com/assets/1324225/10730635/db5f07ac-7bf9-11e5-8f00-c0d625394b0a.png)

https://botwiki.org/bots/twitterbots/DeepForger

![image](https://cloud.githubusercontent.com/assets/1324225/10730652/e6e836a2-7bf9-11e5-9ea2-c72da39a273b.png)

https://botwiki.org/bots/twitterbots/MMecharin

![image](https://cloud.githubusercontent.com/assets/1324225/10730656/eebf1ac6-7bf9-11e5-8f71-9b38d8f6f08d.png)

https://botwiki.org/bots/twitterbots/dscovr_epic

![image](https://cloud.githubusercontent.com/assets/1324225/10730658/f54b25b0-7bf9-11e5-83f1-01c7a2de4a3b.png)

https://botwiki.org/bots/twitterbots/wayback_exe

![image](https://cloud.githubusercontent.com/assets/1324225/10730661/fa9ce864-7bf9-11e5-8293-ecad8cf3ad8a.png)

https://botwiki.org/bots/twitterbots/thenewharperlee

**Comment by stefanbohacek** [comment]
Yes, I noticed this and I've been a bit too busy to fix these manually (which I did a few times). I'll look into increasing this and try to fix these manually more often.

Thanks!
